services:
  app:
    image: '${ALIAS}-image'
    container_name: ${ALIAS}
    restart: always
    volumes:
      - ./.env:/usr/project/.env
    environment:
      - DISCORD_TOKEN
      - CHECK_MODE

    entrypoint: /usr/project/app